mqtt:
  type: dict
  required: yes
  schema:
    host:
      type: string
      empty: no
      required: no
      default: localhost
    port:
      type: integer
      min: 0
      max: 65535
      required: no
      default: 1883
    user:
      type: string
      required: no
      default: ""
    password:
      type: string
      required: no
      default: ""
    topic_prefix:
      type: string
      required: no
      default: ""
      coerce: rstrip_slash
    protocol:
      type: string
      required: no
      empty: no
      coerce: tostring
      default: "3.1.1"
      allowed:
        - "3.1"
        - "3.1.1"
    status_topic:
      type: string
      required: no
      default: status
    status_payload_running:
      type: string
      required: no
      default: running
    status_payload_stopped:
      type: string
      required: no
      default: stopped
    status_payload_dead:
      type: string
      required: no
      default: dead

gpio_modules:
  type: list
  required: yes
  schema:
    type: dict
    allow_unknown: yes
    schema:
      name:
        type: string
        required: yes
        empty: no
      module:
        type: string
        required: yes
        empty: no
      cleanup:
        type: boolean
        required: no
        default: yes

digital_inputs:
  type: dict
  required: no
  default: {}
  schema:
    type: dict
    schema:

      module:
        type: string
        required: yes
        empty: no

      pin:
        type: integer
        required: yes
        min: 0

      type:
        type: string
        required: no
        default: polling
        allowed:
          - polling
          - interrupt_rising  # Sets up an interrupt and publishes on rising edge
          - interrupt_falling  # Same as above, but falling edge
          - interrupt_both  # Same as above, but both rising and falling edges

      poll_interval:
        type: number
        required: no
        default: 0.1
        min: 0.01

      publish:
        type: string
        required: no
        default: on_change
        allowed:
          - on_change
          - always

      on_payload:
        type: string
        required: no
        empty: no
        default: "ON"

      off_payload:
        type: string
        required: no
        empty: no
        default: "OFF"

      pullup:
        type: boolean
        required: no
        default: no

      pulldown:
        type: boolean
        required: no
        default: no

analog_inputs:
  type: dict
  required: no
  default: {}
  schema:
    type: dict
    schema:

      module:
        type: string
        required: yes
        empty: no

      pin:
        type: integer
        required: yes
        min: 0

      poll_interval:
        type: number
        required: no
        default: 0.1
        min: 0.01

      change_percent:
        type: number
        required: no
        default: 5

      normalized:
        type: boolean
        required: no
        default: yes

outputs:
  type: dict
  required: no
  default: {}
  schema:
    type: dict
    schema:

      module:
        type: string
        required: yes
        empty: no

      pin:
        type: integer
        required: yes
        min: 0

      on_payload:
        type: string
        required: no
        empty: no
        default: "ON"

      off_payload:
        type: string
        required: no
        empty: no
        default: "OFF"

      inverted:
        type: boolean
        required: no
        default: no

      initial:
        type: string
        required: no
        allowed:
          - high
          - low

      initial_pwm:
        type: dict
        required: no
        default: {}
        schema:

          enabled:
            type: boolean
            required: no
            default: yes

          frequency:
            type: number
            required: yes

          duty_cycle:
            type: number
            required: no
            min: 0
            max: 100
            default: 50
