mqtt:
  type: dict
  required: yes
  schema:
    host:
      type: string
      empty: no
    port:
      type: integer
      min: 1
      max: 65535
    user:
      type: string
      required: no
    password:
      type: string
      required: no
    topic_prefix:
      type: string
      coerce: rstrip_slash

gpio_modules:
  type: list
  required: yes
  schema:
    type: dict
    allow_unknown: yes
    schema:
      name:
        type: string
        required: yes
        empty: no
      module:
        type: string
        required: yes
        empty: no

digital_inputs:
  type: list
  required: no
  schema:
    type: dict
    schema:
      name:
        type: string
        required: yes
      module:
        type: string
        required: yes
      pin:
        type: integer
        required: yes
        min: 0
      on_payload:
        type: string
        required: no
        empty: no
      off_payload:
        type: string
        required: no
        empty: no
      pullup:
        type: boolean
        required: no
      pulldown:
        type: boolean
        required: no

digital_outputs:
  type: list
  required: no
  schema:
    type: dict
    schema:
      name:
        type: string
        required: yes
      module:
        type: string
        required: yes
      pin:
        type: integer
        required: yes
        min: 0
      on_payload:
        type: string
        required: no
        empty: no
      off_payload:
        type: string
        required: no
        empty: no